# file: utils/translator.py

import streamlit as st

class Translator:
    def __init__(self):
        self.translations = {
            "English": {
                "app_subheader": "A Complete Healthcare Solution for All",
                "language_header": "Language",
                "language_select_label": "Select Language",
                "user_login_header": "User Login",
                "login_tab": "Login",
                "register_tab": "Register",
                "email": "Email",
                "password": "Password",
                "login_button": "Login",
                "login_success": "Login successful!",
                "invalid_credentials": "Invalid email or password",
                "create_account_subheader": "Create New Account",
                "full_name": "Full Name",
                "phone_number": "Phone Number",
                "age": "Age",
                "gender": "Gender",
                "male": "Male",
                "female": "Female",
                "other": "Other",
                "confirm_password": "Confirm Password",
                "register_button": "Register",
                "passwords_no_match": "❌ Passwords do not match",
                "password_too_short": "❌ Password must be at least 8 characters",
                "invalid_email": "❌ Invalid email format",
                "invalid_phone": "❌ Invalid phone number format",
                "fill_all_fields": "❌ Please fill all required fields",
                "registration_success": "Registration successful! Logging you in...",
                "email_exists": "❌ An account with this email already exists",
                "welcome_message": "Welcome, {name}!",
                "logout_button": "Logout",
                "welcome_header": "Welcome to HEALTHTECH",
                "dashboard_title": "Dashboard - Welcome {name}!",
                "quick_actions": "Quick Actions",
                "donate_blood": "Donate Blood",
                "ai_assistant": "AI Assistant",
                "book_consultation": "Book Consultation",
                "emergency": "Emergency",
                "health_overview": "Your Health Overview",
                "no_health_records": "No health records found. Start tracking your health metrics!",
                "health_goals": "Health Goals",
                "todays_recommendations": "Today's Recommendations:",
                "weekly_summary": "Weekly Summary",
                "steps": "Steps",
                "sleep": "Sleep",
                "water": "Water",
                "exercise": "Exercise",
                "recent_notifications": "Recent Notifications",
                "no_notifications": "You have no new notifications.",
            },
            "Tamil": {
                "app_subheader": "அனைவருக்கும் ஒரு முழுமையான சுகாதார தீர்வு",
                "language_header": "மொழி",
                "language_select_label": "மொழியைத் தேர்ந்தெடுக்கவும்",
                "user_login_header": "பயனர் உள்நுழைவு",
                "login_tab": "உள்நுழைக",
                "register_tab": "பதிவு செய்யவும்",
                "email": "மின்னஞ்சல்",
                "password": "கடவுச்சொல்",
                "login_button": "உள்நுழைக",
                "login_success": "வெற்றிகரமாக உள்நுழைந்துவிட்டீர்கள்!",
                "invalid_credentials": "தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்",
                "create_account_subheader": "புதிய கணக்கை உருவாக்கவும்",
                "full_name": "முழு பெயர்",
                "phone_number": "தொலைபேசி எண்",
                "age": "வயது",
                "gender": "பாலினம்",
                "male": "ஆண்",
                "female": "பெண்",
                "other": "மற்றவை",
                "confirm_password": "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
                "register_button": "பதிவு செய்யவும்",
                "passwords_no_match": "❌ கடவுச்சொற்கள் பொருந்தவில்லை",
                "password_too_short": "❌ கடவுச்சொல் குறைந்தது 8 எழுத்துகள் கொண்டிருக்க வேண்டும்",
                "invalid_email": "❌ தவறான மின்னஞ்சல் வடிவம்",
                "invalid_phone": "❌ தவறான தொலைபேசி எண் வடிவம்",
                "fill_all_fields": "❌ தேவையான அனைத்து புலங்களையும் நிரப்பவும்",
                "registration_success": "பதிவு வெற்றி! உங்களை உள்நுழைக்கிறோம்...",
                "email_exists": "❌ இந்த மின்னஞ்சலில் ஏற்கனவே ஒரு கணக்கு உள்ளது",
                "welcome_message": "வாருங்கள், {name}!",
                "logout_button": "வெளியேறு",
                "welcome_header": "ஹெல்த்டெக்-க்கு வரவேற்கிறோம்",
                "dashboard_title": "முகப்புப் பலகை - வாருங்கள் {name}!",
                "quick_actions": "விரைவுச் செயல்பாடுகள்",
                "donate_blood": "இரத்த தானம்",
                "ai_assistant": "AI உதவியாளர்",
                "book_consultation": "ஆலோசனை பதிவு",
                "emergency": "அவசரம்",
                "health_overview": "உங்கள் சுகாதார கண்ணோட்டம்",
                "no_health_records": "சுகாதாரப் பதிவுகள் எதுவும் இல்லை. உங்கள் சுகாதார அளவீடுகளைக் கண்காணிக்கத் தொடங்குங்கள்!",
                "health_goals": "சுகாதார இலக்குகள்",
                "todays_recommendations": "இன்றைய பரிந்துரைகள்:",
                "weekly_summary": "வாராந்திர சுருக்கம்",
                "steps": "படிகள்",
                "sleep": "தூக்கம்",
                "water": "தண்ணீர்",
                "exercise": "உடற்பயிற்சி",
                "recent_notifications": "சமீபத்திய அறிவிப்புகள்",
                "no_notifications": "உங்களுக்கு புதிய அறிவிப்புகள் எதுவும் இல்லை.",
            },
            "Hindi": {
                # Hindi translations remain here

                "app_subheader": "सभी के लिए एक संपूर्ण स्वास्थ्य सेवा समाधान",
                "language_header": "भाषा",
                "language_select_label": "भाषा चुनें",
                "user_login_header": "उपयोगकर्ता लॉगिन",
                "login_tab": "लॉगिन",
                "register_tab": "पंजीकरण करें",
                "email": "ईमेल",
                "password": "पासवर्ड",
                "login_button": "लॉगिन करें",
                "login_success": "लॉगिन सफल!",
                "invalid_credentials": "अमान्य ईमेल या पासवर्ड",
                "create_account_subheader": "नया खाता बनाएं",
                "full_name": "पूरा नाम",
                "phone_number": "फ़ोन नंबर",
                "age": "आयु",
                "gender": "लिंग",
                "male": "पुरुष",
                "female": "महिला",
                "other": "अन्य",
                "confirm_password": "पासवर्ड की पुष्टि करें",
                "register_button": "पंजीकरण करें",
                "passwords_no_match": "❌ पासवर्ड मेल नहीं खाते",
                "password_too_short": "❌ पासवर्ड कम से कम 8 अक्षरों का होना चाहिए",
                "invalid_email": "❌ अमान्य ईमेल प्रारूप",
                "invalid_phone": "❌ अमान्य फ़ोन नंबर प्रारूप",
                "fill_all_fields": "❌ कृपया सभी आवश्यक फ़ील्ड भरें",
                "registration_success": "पंजीकरण सफल! आपको लॉग इन किया जा रहा है...",
                "email_exists": "❌ इस ईमेल से एक खाता पहले से मौजूद है",
                "welcome_message": "नमस्ते, {name}!",
                "logout_button": "लॉग आउट",
                "dashboard_title": "डैशबोर्ड - नमस्ते {name}!",
            },
            "Spanish": {
                # Spanish translations remain here

                "app_subheader": "Una solución sanitaria completa para todos",
                "language_header": "Idioma",
                "language_select_label": "Seleccione el idioma",
                "user_login_header": "Inicio de sesión de usuario",
                "login_tab": "Iniciar sesión",
                "register_tab": "Registrarse",
                "email": "Correo electrónico",
                "password": "Contraseña",
                "login_button": "Iniciar sesión",
                "login_success": "¡Inicio de sesión exitoso!",
                "invalid_credentials": "Correo electrónico o contraseña no válidos",
                "create_account_subheader": "Crear una nueva cuenta",
                "full_name": "Nombre completo",
                "phone_number": "Número de teléfono",
                "age": "Edad",
                "gender": "Género",
                "male": "Masculino",
                "female": "Femenino",
                "other": "Otro",
                "confirm_password": "Confirmar contraseña",
                "register_button": "Registrarse",
                "passwords_no_match": "❌ Las contraseñas no coinciden",
                "password_too_short": "❌ La contraseña debe tener al menos 8 caracteres",
                "invalid_email": "❌ Formato de correo electrónico no válido",
                "invalid_phone": "❌ Formato de número de teléfono no válido",
                "fill_all_fields": "❌ Por favor, rellene todos los campos obligatorios",
                "registration_success": "¡Registro exitoso! Iniciando sesión...",
                "email_exists": "❌ Ya existe una cuenta con este correo electrónico",
                "welcome_message": "¡Bienvenido, {name}!",
                "logout_button": "Cerrar sesión",
                "dashboard_title": "Panel - ¡Bienvenido {name}!",
            }
        }
        self.language = "English"

    def set_language(self, language):
        self.language = language

    def get(self, key, **kwargs):
        lang_dict = self.translations.get(self.language, self.translations["English"])
        text = lang_dict.get(key, key) # Fallback to key if not found
        return text.format(**kwargs)